"""Fail-closed, machine-independent inputs for corrected training (v3).

Manifests contain relative file IDs and exact historical crop coordinates, not
machine paths. They are prepared explicitly, never generated by training.
"""
import hashlib
import json
from pathlib import Path, PurePosixPath

import numpy as np

PROTOCOL_ID = 'ai_forestwatch_3seed_fp32_v3'


def load_checkpoint(path, map_location='cpu'):
    """Load trusted local checkpoints with pathlib metadata from either OS."""
    import os
    import pathlib
    import torch
    incompatible = 'PosixPath' if os.name == 'nt' else 'WindowsPath'
    compatible = pathlib.WindowsPath if os.name == 'nt' else pathlib.PosixPath
    original = getattr(pathlib, incompatible)
    try:
        setattr(pathlib, incompatible, compatible)
        return torch.load(path, map_location=map_location, weights_only=False)
    finally:
        setattr(pathlib, incompatible, original)


def sha256_file(path):
    digest = hashlib.sha256()
    with open(path, 'rb') as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b''):
            digest.update(block)
    return digest.hexdigest()


def read_pinned_json(path, expected_hash):
    if not path or not expected_hash:
        raise ValueError('A frozen artifact path and pinned SHA-256 are required')
    payload = Path(path).read_bytes()  # missing is deliberately fatal
    actual = hashlib.sha256(payload).hexdigest()
    if actual != expected_hash.lower():
        raise ValueError(f'Artifact SHA-256 mismatch: {path}; expected {expected_hash}, got {actual}')
    return json.loads(payload)


def source_path(data_dir, file_id):
    rel = PurePosixPath(file_id)
    if rel.is_absolute() or '..' in rel.parts or '\\' in file_id or ':' in file_id:
        raise ValueError(f'Unsafe manifest file ID: {file_id}')
    root = Path(data_dir).resolve()
    path = (root / file_id).resolve()
    if not path.is_relative_to(root):
        raise ValueError(f'Manifest file escapes data root: {file_id}')
    return path


def load_manifest(path, expected_hash, data_dir, crop_size, verify_content=True):
    manifest = read_pinned_json(path, expected_hash)
    if manifest.get('schema_version') != 1 or manifest.get('crop_size') != crop_size:
        raise ValueError('Unsupported split schema or mismatched crop size')
    files = manifest['files']
    seen = set()
    seen_hashes = set()
    for mode in ('train', 'val', 'test'):
        split = manifest['splits'][mode]
        ids = split['file_ids']
        if not ids or len(set(ids)) != len(ids) or seen.intersection(ids):
            raise ValueError('Empty, duplicate or overlapping split file IDs')
        hashes = {files[file_id]['sha256'] for file_id in ids}
        if seen_hashes.intersection(hashes):
            raise ValueError('Identical source content appears in different splits')
        seen.update(ids)
        seen_hashes.update(hashes)
        if not split['samples']:
            raise ValueError(f'Empty split samples: {mode}')
        sample_set = set()
        for index, row, col in split['samples']:
            if not all(type(v) is int for v in (index, row, col)) or not 0 <= index < len(ids):
                raise ValueError('Invalid manifest sample index')
            h, w = files[ids[index]]['shape'][:2]
            if row < 0 or col < 0 or row + crop_size > h or col + crop_size > w:
                raise ValueError('Manifest crop lies outside source image')
            if (index, row, col) in sample_set:
                raise ValueError('Duplicate crop within split')
            sample_set.add((index, row, col))
    if seen != set(files):
        raise ValueError('Manifest source table and splits differ')
    for file_id, metadata in files.items():
        local = source_path(data_dir, file_id)
        if not local.is_file():
            raise FileNotFoundError(f'Manifest source is missing: {local}')
        if verify_content and sha256_file(local) != metadata['sha256']:
            raise ValueError(f'Dataset content SHA-256 mismatch: {file_id}')
    return manifest


def load_normalization(path, expected_hash, split_hash, bands):
    stats = read_pinned_json(path, expected_hash)
    if (stats.get('schema_version') != 1 or stats.get('split_sha256') != split_hash
            or stats.get('population') != 'label_1_or_2_finite_nonzero_training_pixels'
            or stats.get('valid_pixels', 0) <= 0):
        raise ValueError('Normalization does not match the frozen training population')
    indices = [stats['bands'].index(band) for band in bands]
    mean = np.asarray(stats['mean'], dtype=np.float64)[indices]
    std = np.asarray(stats['std'], dtype=np.float64)[indices]
    if not np.isfinite(mean).all() or not np.isfinite(std).all() or (std <= 0).any():
        raise ValueError('Invalid normalization mean/std')
    return mean.astype(np.float32), std.astype(np.float32)


def validate_training_config(config, verify_content=True):
    if config.get('protocol_id') != PROTOCOL_ID:
        raise ValueError('Legacy training protocol blocked. Use a config from '
                         'config/protocol_v3; do not resume legacy runs under v3.')
    args = config['train_data_loader']['args']
    trainer = config['trainer']
    if (trainer.get('amp') is not False or trainer.get('precision', 'fp32') != 'fp32'
            or trainer.get('mask_unknown_labels') is not True
            or trainer.get('monitor') != 'min val_loss'
            or trainer.get('early_stop') != 10
            or trainer.get('unknown_label', 0) != 0 or trainer.get('ignore_index', -100) != -100):
        raise ValueError('v3 requires strict FP32, unknown masking, min val_loss monitoring, '
                         'and early-stopping patience=10')
    if any(config['arch']['args'].get(k) is not None for k in ('input_mean', 'input_std')):
        raise ValueError('v3 normalizes in the shared data pipeline; remove architecture normalization')
    if args.get('input_clip') != 10.0:
        raise ValueError('v3 retains input_clip=10.0')
    if len(args['bands']) != config['arch']['args']['input_channels']:
        raise ValueError('Input channel count does not match selected bands')
    if config['arch']['type'] == 'CustomSegformer':
        optimizer = config['optimizer']
        optimizer_args = optimizer.get('args', {})
        scheduler = config['lr_scheduler']
        scheduler_args = scheduler.get('args', {})
        if (optimizer.get('type') != 'AdamW'
                or optimizer_args.get('lr') != 6e-5
                or tuple(optimizer_args.get('betas', ())) != (0.9, 0.999)
                or optimizer_args.get('weight_decay') != 0.01):
            raise ValueError(
                'CustomSegformer requires AdamW(lr=6e-5, betas=(0.9, 0.999), '
                'weight_decay=0.01)'
            )
        if (scheduler.get('type') != 'WarmupPolynomialLR'
                or scheduler.get('interval') != 'step'
                or scheduler_args.get('warmup_ratio') != 0.05
                or scheduler_args.get('power') != 1.0):
            raise ValueError(
                'CustomSegformer requires step-based polynomial decay '
                '(power=1.0) with 5% linear warmup'
            )
        if (args.get('batch_size') != 32 or trainer.get('epochs') != 60
                or config.get('loss') != 'focal_loss2d'
                or config['arch']['args'].get('encoder_pretrained') is not True
                or not config['arch']['args'].get('base_model', '').startswith('nvidia/mit-')):
            raise ValueError(
                'CustomSegformer requires pretrained MiT, batch_size=32, '
                'focal_loss2d and max epochs=60'
            )
    manifest = load_manifest(args.get('split_manifest'), args.get('split_manifest_sha256'),
                             args['data_dir'], args['model_input_size'], verify_content)
    load_normalization(args.get('normalization_path'), args.get('normalization_sha256'),
                       args['split_manifest_sha256'], args['bands'])
    return manifest


def assert_resume_compatible(config, previous):
    """Refuse protocol/config migration within an existing run directory."""
    if previous.get('protocol_id') != PROTOCOL_ID:
        raise ValueError('Cannot resume a legacy checkpoint using corrected v3 semantics')
    for key in ('protocol_id', 'arch', 'seed', 'optimizer', 'lr_scheduler', 'loss'):
        if config.get(key) != previous.get(key):
            raise ValueError(f'Resume configuration mismatch: {key}')
    current_args = dict(config['train_data_loader']['args'])
    old_args = dict(previous['train_data_loader']['args'])
    for args in (current_args, old_args):
        for key in ('data_dir', 'data_split_lists_path', 'num_workers', 'split_manifest', 'normalization_path'):
            args.pop(key, None)  # local paths may change; pinned content may not
    if current_args != old_args:
        raise ValueError('Resume data/preprocessing configuration mismatch')
    for key in ('amp', 'precision', 'mask_unknown_labels', 'unknown_label', 'ignore_index',
                'monitor', 'early_stop', 'epochs'):
        if config['trainer'].get(key) != previous['trainer'].get(key):
            raise ValueError(f'Resume trainer configuration mismatch: {key}')
